// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Subscriber.protoc
// Protobuf Java Version: 4.29.1

public final class SubscriberProtoc {
  private SubscriberProtoc() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      SubscriberProtoc.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscriberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Subscriber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ID = 1;</code>
     * @return The iD.
     */
    int getID();

    /**
     * <code>string name_surname = 2;</code>
     * @return The nameSurname.
     */
    java.lang.String getNameSurname();
    /**
     * <code>string name_surname = 2;</code>
     * @return The bytes for nameSurname.
     */
    com.google.protobuf.ByteString
        getNameSurnameBytes();

    /**
     * <code>.Subscriber.Demand demand = 3;</code>
     * @return The enum numeric value on the wire for demand.
     */
    int getDemandValue();
    /**
     * <code>.Subscriber.Demand demand = 3;</code>
     * @return The demand.
     */
    SubscriberProtoc.Subscriber.Demand getDemand();
  }
  /**
   * Protobuf type {@code Subscriber}
   */
  public static final class Subscriber extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Subscriber)
      SubscriberOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        Subscriber.class.getName());
    }
    // Use Subscriber.newBuilder() to construct.
    private Subscriber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Subscriber() {
      nameSurname_ = "";
      demand_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SubscriberProtoc.internal_static_Subscriber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SubscriberProtoc.internal_static_Subscriber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscriberProtoc.Subscriber.class, SubscriberProtoc.Subscriber.Builder.class);
    }

    /**
     * Protobuf enum {@code Subscriber.Demand}
     */
    public enum Demand
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUBS = 0;</code>
       */
      SUBS(0),
      /**
       * <code>DEL = 1;</code>
       */
      DEL(1),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 1,
          /* suffix= */ "",
          Demand.class.getName());
      }
      /**
       * <code>SUBS = 0;</code>
       */
      public static final int SUBS_VALUE = 0;
      /**
       * <code>DEL = 1;</code>
       */
      public static final int DEL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Demand valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Demand forNumber(int value) {
        switch (value) {
          case 0: return SUBS;
          case 1: return DEL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Demand>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Demand> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Demand>() {
              public Demand findValueByNumber(int number) {
                return Demand.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return SubscriberProtoc.Subscriber.getDescriptor().getEnumTypes().get(0);
      }

      private static final Demand[] VALUES = values();

      public static Demand valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Demand(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Subscriber.Demand)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int iD_ = 0;
    /**
     * <code>int32 ID = 1;</code>
     * @return The iD.
     */
    @java.lang.Override
    public int getID() {
      return iD_;
    }

    public static final int NAME_SURNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nameSurname_ = "";
    /**
     * <code>string name_surname = 2;</code>
     * @return The nameSurname.
     */
    @java.lang.Override
    public java.lang.String getNameSurname() {
      java.lang.Object ref = nameSurname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameSurname_ = s;
        return s;
      }
    }
    /**
     * <code>string name_surname = 2;</code>
     * @return The bytes for nameSurname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameSurnameBytes() {
      java.lang.Object ref = nameSurname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameSurname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEMAND_FIELD_NUMBER = 3;
    private int demand_ = 0;
    /**
     * <code>.Subscriber.Demand demand = 3;</code>
     * @return The enum numeric value on the wire for demand.
     */
    @java.lang.Override public int getDemandValue() {
      return demand_;
    }
    /**
     * <code>.Subscriber.Demand demand = 3;</code>
     * @return The demand.
     */
    @java.lang.Override public SubscriberProtoc.Subscriber.Demand getDemand() {
      SubscriberProtoc.Subscriber.Demand result = SubscriberProtoc.Subscriber.Demand.forNumber(demand_);
      return result == null ? SubscriberProtoc.Subscriber.Demand.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iD_ != 0) {
        output.writeInt32(1, iD_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameSurname_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, nameSurname_);
      }
      if (demand_ != SubscriberProtoc.Subscriber.Demand.SUBS.getNumber()) {
        output.writeEnum(3, demand_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iD_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameSurname_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nameSurname_);
      }
      if (demand_ != SubscriberProtoc.Subscriber.Demand.SUBS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, demand_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SubscriberProtoc.Subscriber)) {
        return super.equals(obj);
      }
      SubscriberProtoc.Subscriber other = (SubscriberProtoc.Subscriber) obj;

      if (getID()
          != other.getID()) return false;
      if (!getNameSurname()
          .equals(other.getNameSurname())) return false;
      if (demand_ != other.demand_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID();
      hash = (37 * hash) + NAME_SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNameSurname().hashCode();
      hash = (37 * hash) + DEMAND_FIELD_NUMBER;
      hash = (53 * hash) + demand_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SubscriberProtoc.Subscriber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscriberProtoc.Subscriber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscriberProtoc.Subscriber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscriberProtoc.Subscriber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscriberProtoc.Subscriber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscriberProtoc.Subscriber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscriberProtoc.Subscriber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static SubscriberProtoc.Subscriber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SubscriberProtoc.Subscriber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SubscriberProtoc.Subscriber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SubscriberProtoc.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static SubscriberProtoc.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SubscriberProtoc.Subscriber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Subscriber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Subscriber)
        SubscriberProtoc.SubscriberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SubscriberProtoc.internal_static_Subscriber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SubscriberProtoc.internal_static_Subscriber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SubscriberProtoc.Subscriber.class, SubscriberProtoc.Subscriber.Builder.class);
      }

      // Construct using SubscriberProtoc.Subscriber.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        iD_ = 0;
        nameSurname_ = "";
        demand_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SubscriberProtoc.internal_static_Subscriber_descriptor;
      }

      @java.lang.Override
      public SubscriberProtoc.Subscriber getDefaultInstanceForType() {
        return SubscriberProtoc.Subscriber.getDefaultInstance();
      }

      @java.lang.Override
      public SubscriberProtoc.Subscriber build() {
        SubscriberProtoc.Subscriber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SubscriberProtoc.Subscriber buildPartial() {
        SubscriberProtoc.Subscriber result = new SubscriberProtoc.Subscriber(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SubscriberProtoc.Subscriber result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.iD_ = iD_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nameSurname_ = nameSurname_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.demand_ = demand_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SubscriberProtoc.Subscriber) {
          return mergeFrom((SubscriberProtoc.Subscriber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SubscriberProtoc.Subscriber other) {
        if (other == SubscriberProtoc.Subscriber.getDefaultInstance()) return this;
        if (other.getID() != 0) {
          setID(other.getID());
        }
        if (!other.getNameSurname().isEmpty()) {
          nameSurname_ = other.nameSurname_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.demand_ != 0) {
          setDemandValue(other.getDemandValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                iD_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                nameSurname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                demand_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int iD_ ;
      /**
       * <code>int32 ID = 1;</code>
       * @return The iD.
       */
      @java.lang.Override
      public int getID() {
        return iD_;
      }
      /**
       * <code>int32 ID = 1;</code>
       * @param value The iD to set.
       * @return This builder for chaining.
       */
      public Builder setID(int value) {

        iD_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iD_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nameSurname_ = "";
      /**
       * <code>string name_surname = 2;</code>
       * @return The nameSurname.
       */
      public java.lang.String getNameSurname() {
        java.lang.Object ref = nameSurname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nameSurname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name_surname = 2;</code>
       * @return The bytes for nameSurname.
       */
      public com.google.protobuf.ByteString
          getNameSurnameBytes() {
        java.lang.Object ref = nameSurname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nameSurname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name_surname = 2;</code>
       * @param value The nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nameSurname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name_surname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNameSurname() {
        nameSurname_ = getDefaultInstance().getNameSurname();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name_surname = 2;</code>
       * @param value The bytes for nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nameSurname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int demand_ = 0;
      /**
       * <code>.Subscriber.Demand demand = 3;</code>
       * @return The enum numeric value on the wire for demand.
       */
      @java.lang.Override public int getDemandValue() {
        return demand_;
      }
      /**
       * <code>.Subscriber.Demand demand = 3;</code>
       * @param value The enum numeric value on the wire for demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemandValue(int value) {
        demand_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.Subscriber.Demand demand = 3;</code>
       * @return The demand.
       */
      @java.lang.Override
      public SubscriberProtoc.Subscriber.Demand getDemand() {
        SubscriberProtoc.Subscriber.Demand result = SubscriberProtoc.Subscriber.Demand.forNumber(demand_);
        return result == null ? SubscriberProtoc.Subscriber.Demand.UNRECOGNIZED : result;
      }
      /**
       * <code>.Subscriber.Demand demand = 3;</code>
       * @param value The demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemand(SubscriberProtoc.Subscriber.Demand value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        demand_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Subscriber.Demand demand = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDemand() {
        bitField0_ = (bitField0_ & ~0x00000004);
        demand_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Subscriber)
    }

    // @@protoc_insertion_point(class_scope:Subscriber)
    private static final SubscriberProtoc.Subscriber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SubscriberProtoc.Subscriber();
    }

    public static SubscriberProtoc.Subscriber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscriber>
        PARSER = new com.google.protobuf.AbstractParser<Subscriber>() {
      @java.lang.Override
      public Subscriber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Subscriber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscriber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SubscriberProtoc.Subscriber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Subscriber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Subscriber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Subscriber.protoc\"o\n\nSubscriber\022\n\n\002ID\030" +
      "\001 \001(\005\022\024\n\014name_surname\030\002 \001(\t\022\"\n\006demand\030\003 " +
      "\001(\0162\022.Subscriber.Demand\"\033\n\006Demand\022\010\n\004SUB" +
      "S\020\000\022\007\n\003DEL\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Subscriber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Subscriber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Subscriber_descriptor,
        new java.lang.String[] { "ID", "NameSurname", "Demand", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
