# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Capacity.proto

require 'google/protobuf'


descriptor_data = "\n\x0e\x43\x61pacity.proto\"9\n\x08\x43\x61pacity\x12\x18\n\x10subscriber_count\x18\x01 \x01(\x05\x12\x13\n\x0bserver_port\x18\x02 \x01(\x05\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Capacity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Capacity").msgclass
